### ISSUE TITLE
Minecraft crashes when the gas station block breaks sometimes

### ISSUE THREAD

**Issue by Neon4UltraPlays** [henkelmax/ultimate-car-mod#74] opened 2021-12-12 05:43 UTC
Dear Developers of Ultimate Car Mod,

I found a bug in the mod that **crashes the game**.

When you break the gas station block **(sometimes)**, it stops and **crashes** the game, closing the game and opening the launcher.
I am in Forge Optifine 1.16.5.

Would you please fix this bug?

**Comment by Neon4UltraPlays** [comment] 2021-12-12 05:54
As I was saying, I am using Forge Optifine 1.16.5 **(optifine because I want to use smooth glass)**

I also have these mods:
Realism Mats Furniture Pack
Mutant's Vehicle Mod
MoreOre
Swords Mod
Prefab
Moving Elevators
**Ultimate Car Mod**
**Ultimate Plane Mod**
Flywheel
Patchouli
Create Mod
Modern Life
More Minecarts
Obfuscate
More Buttons
WorldEdit
MrCrayfish's Furniture Mod
Architectury
Building Wands
Nef Deco Mod
Extra Ores
Thut Core
Thut Crafts
Thut Elevators
ShetiPhian-Core

Crash Report
[crash-2021-12-12_12.37.13-client.txt](https://github.com/henkelmax/ultimate-car-mod/files/7698177/crash-2021-12-12_12.37.13-client.txt)

**Comment by henkelmax** [comment] 2021-12-12 08:15
Duplicate of #5

**Closed by henkelmax** 2021-12-12 08:15 UTC
Labels: bug
