### ISSUE TITLE
Canola crash

### ISSUE THREAD

**Issue by wesleybruce** [henkelmax/ultimate-car-mod#71] opened 2021-11-17 15:04 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
I accidently placed a bucket of canola oil at my feet while trying to set the fluid exporter to that fluid. Its creating a flowing fluid error and a crash. It seems it can't be picked up with a bucket. Logging back in causes the crash to repeat a few seconds later. Also I can't seem to move while standing in the fluid. It appears to be interacting with the eroding entities mod. Turning off that mod fixed it but you need to know about it.  
**Steps to reproduce the issue**
1.  Crouch look at extractor. 
2. Click on the extractor. I thought I had an empty slot selected not the bucket. Derp!
3.  Fluid appears where I am standing. 
4. Can't move, pick up the fluid, etc and the game then crashes. 

**Expected behavior**
Opening the UI of the the extractor. "Not being an idiot with a bucket in my hand."

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).
https://gist.github.com/wesleybruce/f33672d6ce6524aa8d657cba9e7a67a9
**Versions**
- Minecraft version 1.7.5
- Forge version forge-37.0.109
- Mod version 1.10.11

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
It could be interacting with erodingstoneentities so I checked that by turning that mod off. The pool of canola disappeared and no crash.  I will report to that mod too. 

mod:doubledoors, mod:trashslot, mod:endportalrecipe, mod:easy_spikes, mod:beenfo, mod:metalbushesmod, mod:jei, mod:simplylight, mod:ding, mod:ceramicshears, mod:fluidtank, mod:car, mod:woodenhopper, mod:kleeslabs, mod:simplegrinder, mod:pamhc2foodcore, mod:gravestone, mod:collective, mod:clumps, mod:jrftl, mod:journeymap, mod:cookingforblockheads, mod:citadel, mod:alexsmobs, mod:tumbleweed, mod:travelersbackpack, mod:naturescompass, mod:elevatorid , mod:dungeoncrawl, mod:farmingforblockheads, mod:sophisticatedbackpacks , mod:constructionwand, mod:cfm, mod:connectedglass, mod:balm, mod:waterstrainer, mod:productivebees, mod:packingtape, mod:jeresources , mod:flowerseeds, mod:erodingstoneentities, mod:forge, mod:appleskin, mod:aquaculture, mod:fastleafdecay, mod:mx_lib, mod:veinmining, mod:ironchest, mod:glasscutter, mod:mousetweaks, mod:quickharvest, mod:netherportalfix, mod:gbook 

**Screenshots (Optional)**
Screenshots of the issue.
Sorry the crash is too fast to get a good embarrassing picture.

**Comment by henkelmax** [comment] 2021-11-17 15:07
Duplicate of #57 

(https://github.com/MinecraftForge/MinecraftForge/issues/7922)

**Closed by henkelmax** 2021-11-17 15:07 UTC
Labels: bug

**Comment by wesleybruce** [comment] 2021-11-17 15:45
Good I had not found that one listed. fast work thanks.
