### ISSUE TITLE
cars are joined

### ISSUE THREAD

**Issue by Kanlla** [henkelmax/ultimate-car-mod#180] opened 2024-11-15 18:44 UTC
### Bug description

Buneas I have a problem in version 1.20.1 every time I get out of one of the vehicles, the front part of the vehicle is united, I attach a photo.
![2024-11-15_19 39 49](https://github.com/user-attachments/assets/5f93e293-ca11-4a15-9a2f-aa17f38bdf38)

### Minecraft version

1.20.1

### Mod version

1.20.1

### Mod loader and version

Moshist

### Steps to reproduce

![2024-11-15_19 39 49](https://github.com/user-attachments/assets/82b05472-b4db-4a49-8042-0bf0967dd729)

### Log files

https://gist.github.com/Kanlla/b90a4097b2f0537f7b57b4a76ee54fe3

**Comment by henkelmax** [comment] 2024-11-15 23:15
Duplicate of #178

**Closed by henkelmax** 2024-11-15 23:15 UTC
Labels: triage
