### ISSUE TITLE
Game crashes when destroying top part of gas station block

### ISSUE THREAD

**Issue by nolemretaWxd** [henkelmax/ultimate-car-mod#39] opened 2021-03-13 17:54 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
Minecraft crashes after destroying an gas station at top part

**Steps to reproduce the issue**
1. Place an gas station
2. Destroy the top part
3. Game should freeze with no top part visible

**Expected behavior**
Gas station should be destroyed without errors

**Log files**
https://gist.github.com/nolemretaWxd/bc5aed77abdd64b9a013c7d7cce10af4

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.0.48
- Mod version: 1.0.5

**Other mods**
Optifine HD U G7

**Screenshots (Optional)**
Screenshots of the issue.
![image](https://user-images.githubusercontent.com/31414969/111039271-72d6b300-842d-11eb-8665-2591cb10920e.png)

**Comment by henkelmax** [comment] 2021-03-13 17:55
Duplicate of #5

**Closed by henkelmax** 2021-03-13 17:55 UTC
Labels: bug
