### ISSUE TITLE
Gas Station GUI does not open after previously opening

### ISSUE THREAD

**Issue by BurritoLad** [henkelmax/ultimate-car-mod#63] opened 2021-08-24 15:28 UTC
**Bug description**
When you right-click the gas station, its GUI comes up normally. But when you close it and then click it again, the GUI does not come up. Breaking a gas station and placing it again does not fix this.

**Steps to reproduce the issue**
1. Place gas station
2. Open GUI
3. Close GUI
4. Attempt to open GUI again

**Expected behavior**
I expected that the GUI would open again after closing it.

**Log files**
![The logs of this issue occurring.](https://user-images.githubusercontent.com/78869406/130644929-faa3eee8-286b-41ea-ae82-6e3c8db0aeda.png)

**Versions**
- Minecraft version: 1.17.1
- Forge version: 37.0.25
- Mod version: 1.0.2

**Other mods**
A list of the other mods that were installed when this problem occurred: [NuclearCraft/Guns, Rockets, and Atomic Explosions](https://www.curseforge.com/minecraft/mc-mods/atomic-bomb-1-16)

**Screenshots (Optional)**
Screenshots of the issue.
![The screenshot of what I'm doing with the gas station.](https://user-images.githubusercontent.com/78869406/130644665-2c10c483-293a-4f3f-9a76-01fbc8fd551f.png)

**Comment by BurritoLad** [comment] 2021-08-24 15:30
This bug also appears to break all other GUI. Villagers, chests, you name it.

**Comment by henkelmax** [comment] 2021-08-24 16:49
Duplicate of #61.

Please post your logs there. And DON'T post the logs as a screenshot. Use GitHub gist.

Also please update the car mod and forge to the latest version.

**Closed by henkelmax** 2021-08-24 16:49 UTC
Labels: bug
