### ISSUE TITLE
breaking fuel pumps crashes the game

### ISSUE THREAD

**Issue by Placeholders1234** [henkelmax/ultimate-car-mod#28] opened 2021-01-30 12:23 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
the game not to crash

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version
- Forge version
- Mod version

**Other mods**
ultimate plane mod 
suba gear
mining helmet
grave stone

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment] 2021-01-30 12:49
Duplicate of #5

**Closed by henkelmax** 2021-01-30 12:49 UTC
Labels: bug

**Comment by henkelmax** [comment] 2021-01-30 12:51
Also please fill out the complete issue template next time when reporting an issue.
