### ISSUE TITLE
World Crash with Botania Mod, if destroy only the top block from gas station

### ISSUE THREAD

**Issue by SinobinU** [henkelmax/ultimate-car-mod#25] opened 2021-01-20 15:53 UTC
**Bug description**
World Crash with Botania Mod, if only destroy the top block from gas station (Block from U.Car Mod).
Only destroy the top block!

**Steps to reproduce the issue**
1. install botania mod
2. place gas station
3. destroy the top block from gas station

**Log files**
https://gist.github.com/SinobinU/8c36f48b7e71a5dc4390dbdeccdee422

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.0.0
- Mod version: latest

**Other mods**
Modpack, but crash log: Botania Mod

**Comment by henkelmax** [comment] 2021-01-20 17:17
Duplicate of #5

**Closed by henkelmax** 2021-01-20 17:17 UTC
Labels: bug
