### ISSUE TITLE
Fuel pump crashes clients with a null pointer on server when broken.

### ISSUE THREAD

**Issue by EwyBoy** [henkelmax/ultimate-car-mod#29] opened 2021-02-05 16:02 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
Internering / breaking the fuel pump on a server causes a null pointer.
Fuel pump crashes clients with a null pointer on server when broken.

**Steps to reproduce the issue**
1. Fire up a 1.16.5 server.
2. Break a fuel pump.
3. See error: https://pastebin.com/rzcU253h

**Expected behavior**
Break it.

**Log files**
https://pastebin.com/rzcU253h

**Versions**
- 1.16.5
35.1.23
[1.16.4] Ultimate Car Mod 1.16.4-1.0.5

**Other mods**
See crash log if applicable

**Comment by henkelmax** [comment] 2021-02-05 17:59
Duplicate of #5

**Closed by henkelmax** 2021-02-05 17:59 UTC
Labels: bug
